//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authentication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string account { get; set; }
        public string hashedpassword { get; set; }
        public string salt { get; set; }
        public string token { get; set; }
        public System.DateTime periodverify { get; set; }
        public int accountstatus { get; set; }
        public string phonenumber { get; set; }
        public string address { get; set; }
    
        public virtual status status { get; set; }
    }
}
