//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phim
    {
        public phim()
        {
            this.phim_dienvien = new HashSet<phim_dienvien>();
            this.phimitems = new HashSet<phimitem>();
            this.phim_quocgia = new HashSet<phim_quocgia>();
            this.phim_theloaiphim = new HashSet<phim_theloaiphim>();
        }
    
        public int id { get; set; }
        public string tenphim { get; set; }
        public string gioithieuphim { get; set; }
        public System.DateTime ngaycongchieu { get; set; }
        public string daodien { get; set; }
        public int namsanxuat { get; set; }
        public int luotxem { get; set; }
        public double danhgiaphim { get; set; }
        public string anhbiaphim { get; set; }
        public Nullable<int> tongsotap { get; set; }
    
        public virtual ICollection<phim_dienvien> phim_dienvien { get; set; }
        public virtual ICollection<phimitem> phimitems { get; set; }
        public virtual ICollection<phim_quocgia> phim_quocgia { get; set; }
        public virtual ICollection<phim_theloaiphim> phim_theloaiphim { get; set; }
    }
}
