//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quocgia
    {
        public quocgia()
        {
            this.phim_quocgia = new HashSet<phim_quocgia>();
        }
    
        public int id { get; set; }
        public string tenquocgia { get; set; }
    
        public virtual ICollection<phim_quocgia> phim_quocgia { get; set; }
    }
}
