//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class theloaiphim
    {
        public theloaiphim()
        {
            this.phim_theloaiphim = new HashSet<phim_theloaiphim>();
        }
    
        public int id { get; set; }
        public string tentheloai { get; set; }
    
        public virtual ICollection<phim_theloaiphim> phim_theloaiphim { get; set; }
    }
}
