//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_SSO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Country
    {
        public Country()
        {
            this.Contacts = new HashSet<Contact>();
            this.Customers = new HashSet<Customer>();
            this.ForeignAreas = new HashSet<ForeignArea>();
        }
    
        public int CountryId { get; set; }
        public Nullable<int> AreaId { get; set; }

        [DisplayName("Tên Nước")]
        public string Name { get; set; }
        public string Note { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<ForeignArea> ForeignAreas { get; set; }
    }
}
