//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_SSO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailOfTourOrder
    {
        public int Id { get; set; }
        public int TourOrderId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> Note { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual TourOrder TourOrder { get; set; }
    }
}
