//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_SSO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForeignArea
    {
        public ForeignArea()
        {
            this.TourPlaces = new HashSet<TourPlace>();
        }
    
        public int ForeignAreaId { get; set; }
        public string Name { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Note { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<TourPlace> TourPlaces { get; set; }
    }
}
