//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_SSO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallary
    {
        public Gallary()
        {
            this.TourGallaries = new HashSet<TourGallary>();
            this.TourPlaceGallaries = new HashSet<TourPlaceGallary>();
        }
    
        public int ImageId { get; set; }
        public string Path { get; set; }
    
        public virtual ICollection<TourGallary> TourGallaries { get; set; }
        public virtual ICollection<TourPlaceGallary> TourPlaceGallaries { get; set; }
    }
}
