//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_SSO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TourPlace
    {
        public TourPlace()
        {
            this.TourDetails = new HashSet<TourDetail>();
            this.TourPlaceGallaries = new HashSet<TourPlaceGallary>();
        }
    
        public int TourPlaceId { get; set; }

        [DisplayName("Tên Địa Điểm")]
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ForeignAreaId { get; set; }
    
        public virtual ForeignArea ForeignArea { get; set; }
        public virtual ICollection<TourDetail> TourDetails { get; set; }
        public virtual ICollection<TourPlaceGallary> TourPlaceGallaries { get; set; }
    }
}
