//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_SSO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourGallary
    {
        public int Id { get; set; }
        public int TourId { get; set; }
        public int ImageId { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Gallary Gallary { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
