//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_SSO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Tour
    {
        public Tour()
        {
            this.TourDetails = new HashSet<TourDetail>();
            this.TourOrders = new HashSet<TourOrder>();
            this.TourGallaries = new HashSet<TourGallary>();
        }
    

        [DisplayName("TourID")]
        public int TourId { get; set; }

        [DisplayName("Tên Tour")]
        public string Name { get; set; }

        [DisplayName("Giá Tour")]
        public Nullable<double> Price { get; set; }
        public string UnitPrice { get; set; }

        [DisplayName("Hình Ảnh")]
        public string Image { get; set; }

        [DisplayName("Ngày Khởi Hành")]
        public Nullable<System.DateTime> StartDate { get; set; }
        [DisplayName("Ngày Kết Thúc")]
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Days { get; set; }

        [DisplayName("Số Lượng Khách")]
        public Nullable<int> Avaiable { get; set; }

        [DisplayName("Chi tiết Tour")]
        public string Description { get; set; }
        public Nullable<int> Booked { get; set; }

        [DisplayName("Tour Trong, Ngoài Nước")]
        public Nullable<int> InOutType { get; set; }

        [DisplayName("Nơi Khởi Hành")]
        public string Note { get; set; }

        [DisplayName("Tình Trạng")]
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<TourDetail> TourDetails { get; set; }
        public virtual ICollection<TourOrder> TourOrders { get; set; }
        public virtual ICollection<TourGallary> TourGallaries { get; set; }
    }
}
